import { NextResponse } from 'next/server'

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
}

const FALLBACK_AUDIO_URLS: Record<string, string> = {
  '6w97fN5c44E': 'https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3',
  'l1m4E-s1t8Y': 'https://cdn.pixabay.com/download/audio/2022/01/18/audio_d0a13f69d2.mp3',
  'QG802l6XUCA': 'https://cdn.pixabay.com/download/audio/2022/03/15/audio_c8c8a73467.mp3',
  'aJ-LgJc5v_s': 'https://cdn.pixabay.com/download/audio/2022/10/14/audio_9939f7922f.mp3',
  'jR_5908N3kE': 'https://cdn.pixabay.com/download/audio/2021/08/09/audio_884325752c.mp3',
}

const STARTER_CATALOG = [
  {
    id: 'track_1',
    title: 'Aguner Poroshmoni Choyao Prane',
    slug: 'aguner-poroshmoni',
    artistId: 'artist_1',
    artist: {
      id: 'artist_1',
      name: 'Rezwana Choudhury Bannya',
      slug: 'rezwana-choudhury-bannya',
      bio: 'Renowned exponent of Rabindra Sangeet',
      avatarUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
      verified: true,
      monthlyListeners: 850000,
    },
    albumId: 'album_1',
    album: {
      id: 'album_1',
      title: 'Aguner Poroshmoni',
      slug: 'aguner-poroshmoni',
      artistId: 'artist_1',
      coverArtUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
      totalTracks: 1,
      durationMs: 245000,
      albumType: 'SINGLE',
    },
    audioUrl: '/api/stream?videoId=6w97fN5c44E&redirect=1',
    fallbackAudioUrl: FALLBACK_AUDIO_URLS['6w97fN5c44E'],
    youtubeId: '6w97fN5c44E',
    durationMs: 245000,
    trackNumber: 1,
    discNumber: 1,
    explicit: false,
    playCount: 420000,
    isPremium: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'track_2',
    title: 'Shob Loke Koy Lalon Ki Jat',
    slug: 'shob-loke-koy-lalon-ki-jat',
    artistId: 'artist_2',
    artist: {
      id: 'artist_2',
      name: 'Farida Parveen',
      slug: 'farida-parveen',
      bio: 'Legendary Lalon Sangeet vocalist of Bangladesh',
      avatarUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
      verified: true,
      monthlyListeners: 620000,
    },
    albumId: 'album_2',
    album: {
      id: 'album_2',
      title: 'Shob Loke Koy Lalon',
      slug: 'shob-loke-koy-lalon',
      artistId: 'artist_2',
      coverArtUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
      totalTracks: 1,
      durationMs: 310000,
      albumType: 'SINGLE',
    },
    audioUrl: '/api/stream?videoId=l1m4E-s1t8Y&redirect=1',
    fallbackAudioUrl: FALLBACK_AUDIO_URLS['l1m4E-s1t8Y'],
    youtubeId: 'l1m4E-s1t8Y',
    durationMs: 310000,
    trackNumber: 1,
    discNumber: 1,
    explicit: false,
    playCount: 380000,
    isPremium: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'track_3',
    title: 'Nasek Nasek',
    slug: 'nasek-nasek',
    artistId: 'artist_3',
    artist: {
      id: 'artist_3',
      name: 'Coke Studio Bangla',
      slug: 'coke-studio-bangla',
      bio: 'Contemporary Bengali music fusion platform',
      avatarUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
      verified: true,
      monthlyListeners: 2400000,
    },
    albumId: 'album_3',
    album: {
      id: 'album_3',
      title: 'Nasek Nasek (Single)',
      slug: 'nasek-nasek-single',
      artistId: 'artist_3',
      coverArtUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
      totalTracks: 1,
      durationMs: 280000,
      albumType: 'SINGLE',
    },
    audioUrl: '/api/stream?videoId=QG802l6XUCA&redirect=1',
    fallbackAudioUrl: FALLBACK_AUDIO_URLS['QG802l6XUCA'],
    youtubeId: 'QG802l6XUCA',
    durationMs: 280000,
    trackNumber: 1,
    discNumber: 1,
    explicit: false,
    playCount: 1850000,
    isPremium: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'track_4',
    title: 'Hok Kolorob',
    slug: 'hok-kolorob',
    artistId: 'artist_4',
    artist: {
      id: 'artist_4',
      name: 'Arnob',
      slug: 'shayan-chowdhury-arnob',
      bio: 'Bengali musician, singer and composer',
      avatarUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&auto=format&fit=crop&q=80',
      verified: true,
      monthlyListeners: 1100000,
    },
    albumId: 'album_4',
    album: {
      id: 'album_4',
      title: 'Hok Kolorob Album',
      slug: 'hok-kolorob-album',
      artistId: 'artist_4',
      coverArtUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&auto=format&fit=crop&q=80',
      totalTracks: 1,
      durationMs: 225000,
      albumType: 'ALBUM',
    },
    audioUrl: '/api/stream?videoId=aJ-LgJc5v_s&redirect=1',
    fallbackAudioUrl: FALLBACK_AUDIO_URLS['aJ-LgJc5v_s'],
    youtubeId: 'aJ-LgJc5v_s',
    durationMs: 225000,
    trackNumber: 1,
    discNumber: 1,
    explicit: false,
    playCount: 950000,
    isPremium: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'track_5',
    title: 'Karar Oi Louho Kapat',
    slug: 'karar-oi-louho-kapat',
    artistId: 'artist_5',
    artist: {
      id: 'artist_5',
      name: 'Firoza Begum',
      slug: 'firoza-begum',
      bio: 'Iconic Nazrul Geeti singer of the Indian subcontinent',
      avatarUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=600&auto=format&fit=crop&q=80',
      verified: true,
      monthlyListeners: 730000,
    },
    albumId: 'album_5',
    album: {
      id: 'album_5',
      title: 'Karar Oi Louho Kapat',
      slug: 'karar-oi-louho-kapat',
      artistId: 'artist_5',
      coverArtUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=600&auto=format&fit=crop&q=80',
      totalTracks: 1,
      durationMs: 215000,
      albumType: 'SINGLE',
    },
    audioUrl: '/api/stream?videoId=jR_5908N3kE&redirect=1',
    fallbackAudioUrl: FALLBACK_AUDIO_URLS['jR_5908N3kE'],
    youtubeId: 'jR_5908N3kE',
    durationMs: 215000,
    trackNumber: 1,
    discNumber: 1,
    explicit: false,
    playCount: 610000,
    isPremium: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export async function OPTIONS() {
  return new Response(null, { status: 204, headers: CORS_HEADERS })
}

export async function GET() {
  return NextResponse.json(
    { userTracks: [], allTracks: STARTER_CATALOG },
    { headers: CORS_HEADERS }
  )
}
